// Soffos Inc. JavaScript SDK package

const { ServiceString } = require('./common/constants');
// const {
//     AmbiguityDetectionService, 
//     AnswerScoringService, 
//     ContradictionDetectionService,
//     DocumentsIngestService, DocumentsSearchService, DocumentsDeleteService, DocumentsService,
//     EmailAnalysisService,
//     EmotionDetectionService,
//     FileConverterService,
//     LanguageDetectionService,
//     LetsDiscussService,
//     LogicalErrorDetectionService,
//     MicrolessonService,
//     NamedEntityRecognitionService,
//     ParaphraseService,
//     ProfanityService,
//     QuestionAndAnswerGenerationService,
//     QuestionAnsweringService,
//     ReviewTaggerService,
//     SentimentAnalysisService,
//     SimplifyService,
//     SummarizationService,
//     TableGeneratorService,
//     TagGenerationService,
//     TranscriptCorrectionService,
// } = require('./core/services');

const apiKey = process.env.SOFFOSAI_API_KEY;

module.exports = {
    apiKey,
    ServiceString,
    // AmbiguityDetectionService, 
    // AnswerScoringService, 
    // ContradictionDetectionService,
    // DocumentsIngestService, DocumentsSearchService, DocumentsDeleteService, DocumentsService,
    // EmailAnalysisService,
    // EmotionDetectionService,
    // FileConverterService,
    // LanguageDetectionService,
    // LetsDiscussService,
    // LogicalErrorDetectionService,
    // MicrolessonService,
    // NamedEntityRecognitionService,
    // ParaphraseService,
    // ProfanityService,
    // QuestionAndAnswerGenerationService,
    // QuestionAnsweringService,
    // ReviewTaggerService,
    // SentimentAnalysisService,
    // SimplifyService,
    // SummarizationService,
    // TableGeneratorService,
    // TagGenerationService,
    // TranscriptCorrectionService,
};
